### PR TITLE
Fix build-issues

### PR DESCRIPTION
**Pull request by milnet2**
Had some issues building. 
I hope the settings work for all now.

Additionally I'm unsure, if it's a good idea to have the .idea-directory checked in into the repo.

### CODE REVIEW

**Comment by svenmeier** [comment]
I applied some of your changes to the code base and did a clean-up of some other parts.

Could you please try again and check what we could improve further?

Many thanks.

**Comment by milnet2** [comment]
Thanks for the update. Build almost worked now. Only thing I had to do:

Add:
`include ':app'`

In the beginning of _settings.gradle_, so the module was automatically imported into android-studio

**Comment by svenmeier** [comment]
Hm, that's already in there:

https://github.com/svenmeier/coxswain/blob/master/settings.gradle

**Comment by milnet2** [comment]
Uhh, I've just seen that - sorry! Most probably it was my fault when checking out master again.

When hitting the "play" button in android-studio it will still complain:

> Error:Failed to complete Gradle execution.
>
>Cause:
>The version of Gradle you are using (3.3) does not support the forTasks() method on BuildActionExecuter. Support for this is available in Gradle 3.5 and all later versions.

Btw.: I just got my TICKR X working over bluetooth (I still have to see it it works if actually rowing). For that I added an additional implementation on the side of the existing one: Mine will only work with Android Nougat. That's because I'm using CompletableFutures.

**Comment by svenmeier** [comment]
I've just cloned a fresh copy of this repo and build and run worked immediately with Android Studio 2.3.3.

Please open another issue if there's still something missing.

**Pull request closed without merging**
